Repository fdietze/scala-js-d3v4, pull requests merged in 2022-09, with the labels that each got.

#162 Update scalajs-dom to 2.3.0
  build.sbt
Labels: dependency-update

#161 Update sbt-scalajs-bundler to 0.21.0
  project/plugins.sbt
Labels: dependency-update

#164 add -scalajs flag for Scala3
  build.sbt
Labels: ready-to-merge-squash

#154 Update scala3-library_sjs1 to 3.1.3
  .github/workflows/build.yml
  build.sbt
  src/main/scala/Transition.scala
Labels: dependency-update, dependencies, scala
